repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        stages: [ commit ]
        language: system
        entry: make lint
        types: [ python ]

      - id: test
        name: test
        stages: [ commit ]
        language: system
        entry: make test
        types: [ python ]
        pass_filenames: false
